#' Calculate some statistics via Logistic Regression With a Bag of Little Bootstraps Implementation
#' @description
#' We use the bag of little bootstraps algorithm in order to calculate the statistics generated by weighted logistic regression.
#' @param formula an object of class "formula"
#' @param data data frame, list, or environment(iterable)
#' @param m numeric which indicates the number of subsamples. Default is 10.
#' @param B numeric which is bootstrapped samples per subsample. Default is 5000.
#' @param par logical. Indicate whether or not user wants parallelization to be run. FALSE by default.
#' @return blblog returns an object of class blblog
#' @examples
#' fit <- blblog(Species ~ Sepal.Length, data = iris, m = 3, B = 100)
#' @details
#' This function is used to fit a bag of little bootstraps version of logistic regression. `blblog` returns a fitted object of class "blblog, with a size of length two.
#' @export
blblog <- function(formula, data, m = 10, B = 5000, par = FALSE) {
  if(par == FALSE){
    data_list <- split_data(data, m)
    estimates <- map(
      data_list,
      ~ glm_each_subsample(formula = formula, data = ., n = nrow(data), B = B))
    res <- list(estimates = estimates, formula = formula)
    class(res) <- "blblog"
    invisible(res)
  }
  else{
    data_list <- split_data(data, m)
    estimates <- future_map(
      data_list,
      ~ glm_each_subsample(formula = formula, data = ., n = nrow(data), B = B))
    res <- list(estimates = estimates, formula = formula)
    class(res) <- "blblog"
    invisible(res)
  }
}


#' split data into m parts of approximated equal sizes
split_data <- function(data, m) {
  idx <- sample.int(m, nrow(data), replace = TRUE)
  data %>% split(idx)
}


#' compute the estimates
glm_each_subsample <- function(formula, data, n, B){
  # drop the original closure of formula,
  # otherwise the formula will pick a wrong variable from the global scope.
  environment(formula) <- environment()
  m <- model.frame(formula, data)
  X <- model.matrix(formula, m)
  y <- model.response(m)
  replicate(B, glm1(X, y, n), simplify = FALSE)
}


#' compute the regression estimates for a blb dataset
glm1 <- function(X, y, n) {
  freqs <- as.vector(rmultinom(1, n, rep(1, nrow(X))))
  fit <- glm.fit(X, y, freqs, family = binomial())
  list(coef = blbcoef(fit))
}


#' compute the coefficients from fit
blbcoef_log <- function(fit) {
  coef(fit)
}

#' Print out model and the respective formula
#' @description
#' Use this to print out the formula.
#' @param x object of class "blblog"
#' @param ... optional arguments to be passed
#' @return This returns the model and the formula used to fit it.
#' @examples
#' fit <- blblog(Species ~ Sepal.Length, data = iris, m = 3, B = 100)
#' print(fit)
#' @details
#' If the user wants to print out the model and the respective model, using `print` will do just that.
#' @method print blblog
#' @export
print.blblog<- function(x, ...) {
  cat("blblm model:", capture.output(x$formula))
  cat("\n")
}

#' Find the coefficients
#' @description
#' We use the bag of little bootstraps algorithm in order to calculate the statistics generated by weighted logistic regression.
#' @param object an object of class "blblog"
#' @param par logical. Indicate whether or not user wants parallelization to be run. FALSE by default.
#' @param ... optional arguments to be passed
#' @return numeric. Returns the coefficient of the blblog model.
#' @examples
#' fit <- blblog(Species ~ Sepal.Length, data = iris, m = 3, B = 100)
#' coef(fit)
#' @details
#' Using `coef` produces the coefficients used in the bag of little bootsraps algorithm. These coefficients can be used to solve for the log odds raio.
#' @export
#' @method coef blblog
coef.blblog <- function(object, par = FALSE, ...) {
  if(par == FALSE){
    est <- object$estimates
    map_mean(est, ~ map_cbind(., "coef") %>% rowMeans())
  }
  else{
    est <- object$estimates
    future_map_mean(est, ~ map_cbind(., "coef") %>% rowMeans())
  }
}

#' Obtaining Confidence Intervals
#' @description
#' We use this function `confint` in order to find the confidence interval for all variables involved.
#' @param object object of class "blblog"
#' @param parm NULL by default, as it takes the variables obtained from the blblog fit. This should be a vector of characters that user wants to find confidence interval on.
#' @param level numeric. Specify the confidence level
#' @param par logical. Indicate whether or not user wants parallelization to be run. FALSE by default.
#' @param ... optional arguments to be passed
#' @return an interval for the specified confidence level for the variables involved.
#' @examples
#' fit <- blblog(Species ~ Sepal.Length, data = iris, m = 3, B = 100)
#' confint(fit)
#' @details
#' `confint` produces the confidence intervals for the coefficients for the fitted bag of little bootstraps algorithm for logistic regression.
#' @export
#' @method confint blblog
confint.blblog <- function(object, parm = NULL, level = 0.95, par = FALSE, ...) {
  if(par ==FALSE){
    if (is.null(parm)) {
      parm <- attr(terms(object$formula), "term.labels")
    }
    alpha <- 1 - level
    est <- object$estimates
    out <- map_rbind(parm, function(p) {
      map_mean(est, ~ map_dbl(., list("coef", p)) %>% quantile(c(alpha / 2, 1 - alpha / 2)))
    })
    if (is.vector(out)) {
      out <- as.matrix(t(out))
    }
    dimnames(out)[[1]] <- parm
    out
  }
  else{
    if (is.null(parm)) {
      parm <- attr(terms(object$formula), "term.labels")
    }
    alpha <- 1 - level
    est <- object$estimates
    out <- future_map_rbind(parm, function(p) {
      map_mean(est, ~ map_dbl(., list("coef", p)) %>% quantile(c(alpha / 2, 1 - alpha / 2)))
    })
    if (is.vector(out)) {
      out <- as.matrix(t(out))
    }
    dimnames(out)[[1]] <- parm
    out
  }
}

#' Obtain the predictions/prediction intervals
#' @description
#' We use this function `predict` in order to find coefficients for all variables involved. This method works best for binary classification
#' @param object object of class "blblog"
#' @param new_data data frame indicating the new values to be used for prediction
#' @param confidence a logical value, FALSE by default, indicating whether or not user wants the prediction interval in addition to the predicted value
#' @param level numeric specify the level of the prediction interval
#' @param par logical. Indicate whether or not user wants parallelization to be run. FALSE by default.
#' @param type character indicating whether user wants "link", or "response"
#' @param ... optional arguments to be passed
#' @return numeric value indicating the value of the model (if type = "link"), or the probability of a response happening(if type="response")
#' @examples
#' newiris = iris[c(1:100), ]
#' fit = blblog(Species ~ Sepal.Length, data = newiris, m = 2, B = 2)
#' newdata = data.frame(Sepal.Length=c(5.1))
#' predict(fit, newdata, type = "link")
#' fit = blblog(Species ~ Sepal.Length, data = iris, m = 2, B = 2)
#' newdata = data.frame(Sepal.Length=c(5.1))
#' predict(fit, newdata, type = "response")
#' @details
#' `predict` gives two different values for logistic regression, depending on the `type` used. If "response" is given,
#' then `predict` gives the probability that the predicted value belongs to either class 1 or 2. Using "link" gives instead the
#' predicted logit values.
#' @export
#' @method predict blblog
predict.blblog <- function(object, new_data, confidence = FALSE, level = 0.95, par =  FALSE, type = "link", ...){
  est <- object$estimates
  X <- model.matrix(reformulate(attr(terms(object$formula), "term.labels")), new_data)
  if(type == "link" & par == FALSE){
    if (confidence) {
      map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>%
                apply(1, mean_lwr_upr, level = level) %>%
                t())
    } else {
      map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>% rowMeans())
    }
  }
  else if(type == "link" & par == TRUE){
    if (confidence) {
      future_map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>%
                 apply(1, mean_lwr_upr, level = level) %>%
                 t())
    } else {
      future_map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>% rowMeans())
    }
  }

  else if(type == "response" & par == FALSE){
    if (confidence) {
      link = map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>%
                apply(1, mean_lwr_upr, level = level) %>%
                t())
      prob = exp(link)/(1+exp(link))
      prob

    } else {
      link = map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>% rowMeans())
      prob = exp(link)/(1+exp(link))
      prob
      }
  }

  else if(type == "response" & par == TRUE){
    if (confidence) {
      link = future_map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>%
                        apply(1, mean_lwr_upr, level = level) %>%
                        t())
      prob = exp(link)/(1+exp(link))
      prob

    } else {
      link = future_map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>% rowMeans())
      prob = exp(link)/(1+exp(link))
      prob
    }
  }



}




mean_lwr_upr <- function(x, level = 0.95) {
  alpha <- 1 - level
  c(fit = mean(x), quantile(x, c(alpha / 2, 1 - alpha / 2)) %>% set_names(c("lwr", "upr")))
}

future_map_mean <- function(.x, .f, ...) {
  (future_map(.x, .f, ...) %>% reduce(`+`)) / length(.x)
}

map_mean <- function(.x, .f, ...) {
  (map(.x, .f, ...) %>% reduce(`+`)) / length(.x)
}

map_cbind <- function(.x, .f, ...) {
  map(.x, .f, ...) %>% reduce(cbind)
}

future_map_rbind = function(.x, .f, ...){
  future_map(.x, .f, ...) %>% reduce(rbind)
}

map_rbind <- function(.x, .f, ...) {
  map(.x, .f, ...) %>% reduce(rbind)
}