#' Calculate some statistics via Linear Regression With a Bag of Little Bootstraps Implementation
#' @import purrr
#' @import stats
#' @import bench
#' @import furrr
#' @importFrom magrittr %>%
#' @description
#' We use the bag of little bootstraps algorithm in order to calculate the statistics generated by weighted linear regression.
#' @param formula an object of class "formula"
#' @param data data frame, list, or environment(iterable)
#' @param m numeric which indicates the number of subsamples. Default is 10.
#' @param B numeric which is bootstrapped samples per subsample. Default is 5000.
#' @param par logical. By default, this is FALSE, meaning only one core is used. If user wants to use multiple cores, use par=TRUE, and before running this function, please run `plan(multiprocess, workers = w)`, where w is the number of cores on the user's computer.
#' If any warnings emerge and you wish to hide them, be sure to run:`suppressWarnings(plan(multiprocess, workers = w))` and `options(future.rng.onMisuse = "ignore")`
#' @return bblm returns an object of class bblm
#' @examples
#' fit <- blblm(mpg ~ wt * hp, data = mtcars, m = 3, B = 100, par = TRUE)
#' @details
#' The object returned is of class bblm. Obtaining the coefficients and other estimates is similar to obtaining them
"_PACKAGE"


## quiets concerns of R CMD check re: the .'s that appear in pipelines
# from https://github.com/jennybc/googlesheets/blob/master/R/googlesheets.R
utils::globalVariables(c("."))


#' @export
blblm <- function(formula, data, m = 10, B = 5000, par = FALSE) {
  data_list <- split_data(data, m)
  if(par == FALSE){
    estimates <- map(
      data_list,
      ~ lm_each_subsample(formula = formula, data = ., n = nrow(data), B = B))
    res <- list(estimates = estimates, formula = formula)
    class(res) <- "blblm"
    invisible(res)
  }
  else{
    estimates <- future_map(
      data_list,
      ~ lm_each_subsample(formula = formula, data = ., n = nrow(data), B = B))
    res <- list(estimates = estimates, formula = formula)
    class(res) <- "blblm"
    invisible(res)
  }
}


#' split data into m parts of approximated equal sizes
split_data <- function(data, m) {
  idx <- sample.int(m, nrow(data), replace = TRUE)
  data %>% split(idx)
}


#' compute the estimates
lm_each_subsample <- function(formula, data, n, B){
  # drop the original closure of formula,
  # otherwise the formula will pick a wrong variable from the global scope.
  environment(formula) <- environment()
  m <- model.frame(formula, data)
  X <- model.matrix(formula, m)
  y <- model.response(m)
  replicate(B, lm1(X, y, n), simplify = FALSE)
}


#' compute the regression estimates for a blb dataset
lm1 <- function(X, y, n) {
  freqs <- as.vector(rmultinom(1, n, rep(1, nrow(X))))
  fit <- lm.wfit(X, y, freqs)
  list(coef = blbcoef(fit), sigma = blbsigma(fit))
}


#' compute the coefficients from fit
blbcoef <- function(fit) {
  coef(fit)
}


#' compute sigma from fit
blbsigma <- function(fit) {
  p <- fit$rank
  e <- fit$residuals
  w <- fit$weights
  sqrt(sum(w * (e^2)) / (sum(w) - p))
}

#' Print out model and the respective formula
#' @description
#' Use this to print out the formula.
#' @param x object of class "blblm"
#' @param ... optional arguments to be passed
#' @return This returns the model and the formula used to fit it.
#' @examples
#' fit = blblm(mpg ~ hp * wt, data = mtcars, m = 3, B = 100)
#' print(fit)
#' @details
#' If the user wants to print out the model and the respective model, using `print` will do just that
#' @method print blblm
#' @export
print.blblm <- function(x, ...) {
  cat("blblm model:", capture.output(x$formula))
  cat("\n")
}

#' Obtain sigma
#' @description
#' We use this function `sigma.blblm` in order to find coefficients for all variables involved. This is comparable to using `sigma`
#' @param object object of class "blblm"
#' @param par logical FALSE by default. TRUE indicates desire to use parallelization.
#' @return numeric indicating the value for sigma for this model.
#' @export
#' @examples
#' fit = blblm(mpg ~ hp * wt, data = mtcars, m = 3, B = 100)
#' sigma(fit)
#' @method sigma blblm
sigma.blblm <- function(object, confidence = FALSE, level = 0.95, par = FALSE, ...) {
  est <- object$estimates
  sigma <- mean(map_dbl(est, ~ mean(map_dbl(., "sigma"))))
  if (par == FALSE){
    if (confidence) {
      alpha <- 1 - 0.95
      limits <- est %>%
        map_mean(~ quantile(map_dbl(., "sigma"), c(alpha / 2, 1 - alpha / 2))) %>% set_names(NULL)
      return(c(sigma = sigma, lwr = limits[1], upr = limits[2]))
    }
    else {
      return(sigma)
    }
  }
  else{
    if (confidence) {
      alpha <- 1 - 0.95
      limits <- est %>%
        future_map_mean(~ quantile(map_dbl(., "sigma"), c(alpha / 2, 1 - alpha / 2))) %>% set_names(NULL)
      return(c(sigma = sigma, lwr = limits[1], upr = limits[2]))
    }
    else {
      return(sigma)
    }
  }
}

#' Obtain the coefficients
#' @description
#' We use this function `coef.blblm` in order to find coefficients for all variables involved. This is comparable to using `coef`
#' @param object object of class "blblm"
#' @param par logical FALSE by default. TRUE indicates desire to use parallelization.
#' @param ... optional arguments to be passed
#' @return numeric
#' @examples
#' fit = blblm(mpg ~ hp * wt, data = mtcars, m = 3, B = 100)
#' coef(fit)
#' @details
#' `coef` obtains the coefficients generated by fitting the blblm model.
#' @export
#' @method coef blblm
coef.blblm <- function(object, par = FALSE, ...) {
  est <- object$estimates
  if(par == FALSE){
    map_mean(est, ~ map_cbind(., "coef") %>% rowMeans())
  }
  else{
    future_map_mean(est, ~map_cbind(., "coef") %>% rowMeans())
  }
}


#' Obtaining Confidence Intervals
#' @description
#' We use this function `confint.blblm` in order to find the confidence interval for all variables involved. This is comparable to using `confint`
#' @param object object of class "blblm"
#' @param parm NULL by default, as it takes the variables obtained from the blblm fit. This should be a vector of characters that user wants to find confidence interval on.
#' @param level numeric. Specify the confidence level
#' @param par logical. Indicate whether or not user wants parallelization to be run. FALSE by default.
#' @param ... optional arguments to be passed
#' @return interval indicating the confidence interval for the coefficients involved.
#' @examples
#' fit = blblm(mpg ~ hp * wt, data = mtcars, m = 3, B = 100)
#' confint(fit)
#' @details
#' Running `confint` gives the 95%(by default) confidence interval for the respective fitted coefficients.
#' @export
#' @method confint blblm
confint.blblm <- function(object, parm = NULL, level = 0.95, par = FALSE, ...) {
  if(par == FALSE){
    if (is.null(parm)) {
      parm <- attr(terms(object$formula), "term.labels")
    }
    alpha <- 1 - level
    est <- object$estimates
    out <- map_rbind(parm, function(p) {
      map_mean(est, ~ map_dbl(., list("coef", p)) %>% quantile(c(alpha / 2, 1 - alpha / 2)))
    })
    if (is.vector(out)) {
      out <- as.matrix(t(out))
    }
    dimnames(out)[[1]] <- parm
    out
  }
  else{
    if (is.null(parm)) {
      parm <- attr(terms(object$formula), "term.labels")
    }
    alpha <- 1 - level
    est <- object$estimates
    out <- future_map_rbind(parm, function(p) {
      map_mean(est, ~ map_dbl(., list("coef", p)) %>% quantile(c(alpha / 2, 1 - alpha / 2)))
    })
    if (is.vector(out)) {
      out <- as.matrix(t(out))
    }
    dimnames(out)[[1]] <- parm
    out
  }
}


#' Obtain the predictions/prediction intervals
#' @description
#' We use this function `predict.blblm` in order to find coefficients for all variables involved. This is comparable to using `coef`
#' @param object object of class "blblm"
#' @param new_data dataframe indicating the new values to be used for prediction
#' @param confidence a logical value, FALSE by default, indicating whether or not user wants the prediction interval in addition to the predicted value
#' @param level numeric specify the level of the prediction interval
#' @param par FALSE by default. TRUE if user wants to use parallelization
#' @param ... optional arguments to be passed
#' @return numeric value indicating the new prediction. However, if `confidence = TRUE`, this gives both the numeric value of the
#' prediction as well as the prediction interval.
#' @examples
#' fit = blblm(mpg ~ hp * wt, data = mtcars, m = 3, B = 100)
#' predict(fit, data.frame(wt = c(2.5, 3), hp = c(150, 170)))
#' @details
#' `predict` gives the predicted value of the new data value(s). Using `confidence = TRUE`also yields the respective
#' prediction interval.
#' @export
#' @method predict blblm
predict.blblm <- function(object, new_data, confidence = FALSE, level = 0.95, par = FALSE, ...) {
  est <- object$estimates
  X <- model.matrix(reformulate(attr(terms(object$formula), "term.labels")), new_data)
  if(par == FALSE){
    if (confidence) {
      map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>%
                apply(1, mean_lwr_upr, level = level) %>%
                t())
    } else {
      map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>% rowMeans())
    }
  }
  else{
    if (confidence) {
      future_map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>%
                 apply(1, mean_lwr_upr, level = level) %>%
                 t())
    } else {
      future_map_mean(est, ~ map_cbind(., ~ X %*% .$coef) %>% rowMeans())
    }
  }

}


mean_lwr_upr <- function(x, level = 0.95) {
  alpha <- 1 - level
  c(fit = mean(x), quantile(x, c(alpha / 2, 1 - alpha / 2)) %>% set_names(c("lwr", "upr")))
}

future_map_mean <- function(.x, .f, ...) {
  (future_map(.x, .f, ...) %>% reduce(`+`)) / length(.x)
}

map_mean <- function(.x, .f, ...) {
  (map(.x, .f, ...) %>% reduce(`+`)) / length(.x)
}

map_cbind <- function(.x, .f, ...) {
  map(.x, .f, ...) %>% reduce(cbind)
}

future_map_rbind = function(.x, .f, ...){
  future_map(.x, .f, ...) %>% reduce(rbind)
}

map_rbind <- function(.x, .f, ...) {
  map(.x, .f, ...) %>% reduce(rbind)
}

